### ISSUE TITLE
Google deployment manager hierarchical configuration

### ISSUE THREAD

**Issue by varungbt** [GoogleCloudPlatform/deploymentmanager-samples#197]
@ocsig I tried to deploy the hierarchical configuration example from the latest git source

[Hierarchical configuration Deployment Manger Sample
](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/community/hierarchical_configuration)
```
gcloud deployment-manager deployments create hierarchy-example-dev --template env_demo_project.py --properties=envName:dev

The fingerprint of the deployment is RcXh77bYcCp8N7VSG07pOw==
Waiting for create [operation-1532307241170-571a014cbf450-5f1b7bab-473bf037]...failed.
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1532307241170-571a014cbf450-5f1b7bab-473bf037]: errors:
- code: MANIFEST_EXPANSION_USER_ERROR
  location: /deployments/hierarchy-example-dev/manifests/manifest-1532307241298
  message: |-
    Manifest expansion encountered the following errors: Exception in env_demo_project.py
    Traceback (most recent call last):
        return constructor[m](evaluation_context)
      File "<string>", line 7, in GenerateConfig
      File "helper/config_merger.py", line 39, in __init__
      File "helper/config_merger.py", line 67, in getOrgSpecificConfig
      File "helper/config_merger.py", line 61, in loadConfig
    KeyError: 'master_config'
     Resource: env_demo_project.py Resource: config
```
I believe the issue is with the __import__ statement syntax.
Can you please advise if there are any required settings ?

**Comment by ocsig** [comment]
I can verify the syntax is broken, I will fix it during the next few days. I don't have an immediate solution for you.

**Comment by varungbt** [comment]
Thanks for the quick fix.
