### ISSUE TITLE
project can't be created under referenced folder

### ISSUE THREAD

**Issue by marko7460** [GoogleCloudPlatform/deploymentmanager-samples#354]
Example deployment:
```yaml
name: test
imports:
  - path: ../../../deploymentmanager-samples/community/cloud-foundation/templates/folder/folder.py
    name: folder.py
  - path: ../../../deploymentmanager-samples/community/cloud-foundation/templates/project/project.py
    name: project.py

project: {{env.CFT_BOOTSTRAP_PROJECT_ID}}
resources:
  - name: test-folder
    type: folder.py
    properties:
      folders:
        - name: "test"
          orgId: "organizations/{{env.CFT_ORGANIZATION_ID}}"
          displayName: "test"
  - name: test-host-project
    type: project.py
    properties:
      billingAccountId: "{{env.CFT_BILLING_ACCOUNT_ID}}"
      parent:
        type: folder
        id: $(ref.test-folder.folders.test.name)
      activateApis:
        - compute.googleapis.com
        - deploymentmanager.googleapis.com
        - pubsub.googleapis.com
        - container.googleapis.com
      serviceAccounts:
        - accountId: cft-demo-sa-0
          displayName: cft demo service account 0
          roles:
            - roles/editor
            - roles/viewer
          networkAccess: true
      usageExportBucket: false
      sharedVPCHost: true
      removeDefaultVPC: true
```

Run `cft apply test.yaml`. 

Result:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/cloud_foundation_toolkit/cli.py", line 138, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/cloud_foundation_toolkit/cli.py", line 134, in main
    execute(args)
  File "/usr/local/lib/python2.7/site-packages/cloud_foundation_toolkit/actions.py", line 136, in execute
    method(**arguments)
  File "/usr/local/lib/python2.7/site-packages/cloud_foundation_toolkit/deployment.py", line 714, in apply
    self.update(preview=preview)
  File "/usr/local/lib/python2.7/site-packages/cloud_foundation_toolkit/deployment.py", line 606, in update
    func()
  File "/usr/local/lib/python2.7/site-packages/cloud_foundation_toolkit/deployment.py", line 642, in update_preview
    self.wait(operation, 'update preview')
  File "/usr/local/lib/python2.7/site-packages/cloud_foundation_toolkit/deployment.py", line 671, in wait
    base64.urlsafe_b64encode(self.current.fingerprint)
  File "/Users/vlahovic/google-cloud-sdk/lib/googlecloudsdk/command_lib/deployment_manager/dm_write.py", line 127, in WaitForOperation
    operation_name, dm_util.RenderMessageAsYaml(operation.error)))
googlecloudsdk.api_lib.deployment_manager.exceptions.OperationError: Error in Operation [operation-1543443146085-57bc0dc74128b-61745f62-629a7abe]: errors:
- code: RESOURCE_ERROR
  location: /deployments/test/resources/project
  message: '{"ResourceType":"cloudresourcemanager.v1.project","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"field
    [parent] has issue [Parent id must be numeric.]","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"parent","description":"Parent
    id must be numeric."}]},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"url":"https://cloud.google.com/resource-manager/reference/rest/v1/projects"}]}],"statusMessage":"Bad
    Request","requestPath":"https://cloudresourcemanager.googleapis.com/v1/projects","httpMethod":"POST"}}'
```

I'm pretty sure that the problem is that `$(ref.test-folder.folders.test.name)` evaluates to something like this: `folders/123456789`,  while `project` needs `parent.id` to be only integer part of that output: `123456789`

**Comment by ocsig** [comment]
PR #355 got merged into master. This feature fixes the issue with cross deployment references if the referenced output is a complex structure.
